### ISSUE TITLE
Shortcuts in other layouts

### ISSUE THREAD

**Issue by DSOverlord** [nferhat/fht-compositor#18]
Keyboard shortcuts don't work in a layout other than English.

**Comment by nferhat** [comment]
I think depending on which default keybinds it might not work, especially the workspace ones. I was using azerty before and workspace bindings didn't work unless you changed them.

Could you please give me example binds that don't work?

**Comment by nferhat** [comment]
Just tested and it seems to work fine except workspace binds.

**Comment by nferhat** [comment]
For workspace binds you can use the following

```toml
[keybinds]
Super-ampersand  = { action = "focus-workspace", arg = 0 }
Super-eacute     = { action = "focus-workspace", arg = 1 }
Super-quotedbl   = { action = "focus-workspace", arg = 2 }
Super-apostrophe = { action = "focus-workspace", arg = 3 }
Super-parenleft  = { action = "focus-workspace", arg = 4 }
Super-minus      = { action = "focus-workspace", arg = 5 }
Super-egrave     = { action = "focus-workspace", arg = 6 }
Super-underscore = { action = "focus-workspace", arg = 7 }
Super-ccedilla   = { action = "focus-workspace", arg = 8 }
```

**Comment by nferhat** [comment]
@DSOverlord oh wait are you using a latin layout? Because the default config only has latin binds

**Comment by DSOverlord** [comment]
I use the Russian and English layouts in this form:
```nix
input.keyboard = {
    layout = "us,ru";
    options = "grp:alt_shift_toggle";
    repeat-rate = 30;
    repeat-delay = 260;
};
```

**Comment by nferhat** [comment]
Okay, if you want a bind to work in Russian right now you should bind it like

```toml
[keybinds]
Super-XK_Cyrillic_shorti = "close-window"
```

How do other compositors that you used handle such keybinds?
