### ISSUE TITLE
Merging error with outputs configuration

### ISSUE THREAD

**Issue by nferhat** [nferhat/fht-compositor#47]
Let's say you have two files

- `~/.config/fht/compositor.toml`
```toml
imports = ["~/.config/fht/compositor-2.toml"]
outputs.eDP-1.position = [0, 360]
```

- `~/.config/fht/compositor-2.toml`
```toml
outputs.eDP-1.position = [0, 1080]
```

This will make the position attribute take the following value: `[0, 360, 0, 1080]` since when we merge two configuration tables together, we extend the array.
