### ISSUE TITLE
Support Variable Refresh Rate

### ISSUE THREAD

**Issue by nferhat** [nferhat/fht-compositor#49]
VRR is what manufacturers usually call NVidia GSync or Radeon/AMD FreeSync. They allow to dynamically change the display's refresh rate based on what is actually being drawn to get the smoothest result possible, and avoid power draw by drawing at a lower refresh rate.

I currently do not have the hardware to test VRR (I do have a VRR-capable display, but the Vega8 iGPU I have on my laptop is not enough). I should be getting a VRR-capable GPU soon.

When that'll be the case, I'll work on adding it.

## Actual implementation information

Two modes will be available

1. Always enable VRR
```toml
[output.DP-1]
vrr = true # or "always", this will keep VRR always running
```

2. Only enable VRR when a window rule matches
```toml
[output.DP-1]
vrr = "on-demand"

[[rules]]
match-app-id = ["steam_app_*", "Celeste.x86_64"]
vrr = true
```

For a window rule VRR to match, there must be **no** other windows, and it should be scanned out to the primary plane (most likely by being fullscreen)
