### ISSUE TITLE
Focus workspace 9 exits compositor

### ISSUE THREAD

**Issue by jakehamilton** [nferhat/fht-compositor#54]
I am trying out the project on my NixOS machine, but attempting to use a key action for `send-to-workspace` with the argument `9` causes the compositor to exit, putting me back at my login screen (gdm). I would like to make use of all ten number keys to have ten total workspaces.

The single action causing issues is:

```toml
[keybinds.Super-0]
action = "focus-workspace"
arg = 9
```

<details>
  <summary>View Full Config (Nix)</summary>

```nix
  {
    imports = [
      "~/.config/fht/adhoc.toml"
    ];

    autostart = [
      # Support for XDG autostart
      "${lib.getExe pkgs.dex} -a"

      "${lib.getExe term.package}"
    ];

    env = {
      DISPLAY = ":0";
      # Fix up graphical toolkits to work nicely.
      _JAVA_AWT_WM_NONREPARENTING = "1";
      QT_QPA_PLATFORM = "wayland";
      QT_QPA_PLATFORMTHEME = "gtk3";
      QT_STYLE_OVERRIDE = "adwaita";
      MOZ_ENABLE_WAYLAND = "1";
      SDL_VIDEODRIVER = "wayland";
      SDL_BACKEND = "wayland";
    };

    general = {
      cursor-warps = true;
      focus-new-windows = true;

      layouts = [
        # TODO: For large screens we want to use "centered-master" as the default.
        # We should also provide both layouts and an
        # easy way to switch between them at runtime
        # in case an external monitor is attached.
        "tile"
      ];

      outer-gaps = 20;
    };

    input = {
      keyboard = {
        layout = "us";
        options = builtins.concatStringsSep "," [
          "caps:escape"
        ];
        repeat-rate = 50;
        repeat-delay = 200;
      };

      mouse = {
        # TODO: This should be "linear" for desktops.
        acceleration-profile = "adaptive";

        scroll-method = "two-finger";
        click-method = "clickfinger";
        natural-scrolling = true;

        tap-to-click = true;
        tap-button-map = "left-right-middle";

        tap-and-drag = true;
        drag-lock = true;
      };
    };

    keybinds = {
      Super-Return = {
        action = "run-command";
        arg = lib.getExe term.package;
      };

      Super-Control-Shift-q = {
        action = "quit";
      };

      Super-Control-Shift-r = {
        action = "reload-config";
      };

      Super-q = {
        action = "close-focused-window";
      };

      Super-f = {
        action = "fullscreen-focused-window";
      };

      Super-m = {
        action = "maximize-focused-window";
      };

      Super-c = {
        action = "center-floating-window";
      };

      Super-Space = {
        action = "float-focused-window";
      };

      Super-j = {
        action = "focus-next-window";
      };

      Super-k = {
        action = "focus-previous-window";
      };

      Super-Shift-j = {
        action = "swap-with-next-window";
      };

      Super-Shift-k = {
        action = "swap-with-previous-window";
      };

      Super-1 = {
        action = "focus-workspace";
        arg = 0;
      };

      Super-Shift-1 = {
        action = "send-to-workspace";
        arg = 0;
      };

      Super-2 = {
        action = "focus-workspace";
        arg = 1;
      };

      Super-Shift-2 = {
        action = "send-to-workspace";
        arg = 1;
      };

      Super-3 = {
        action = "focus-workspace";
        arg = 2;
      };

      Super-Shift-3 = {
        action = "send-to-workspace";
        arg = 2;
      };

      Super-4 = {
        action = "focus-workspace";
        arg = 3;
      };

      Super-Shift-4 = {
        action = "send-to-workspace";
        arg = 3;
      };

      Super-5 = {
        action = "focus-workspace";
        arg = 4;
      };

      Super-Shift-5 = {
        action = "send-to-workspace";
        arg = 4;
      };

      Super-6 = {
        action = "focus-workspace";
        arg = 5;
      };

      Super-Shift-6 = {
        action = "send-to-workspace";
        arg = 5;
      };

      Super-7 = {
        action = "focus-workspace";
        arg = 6;
      };

      Super-Shift-7 = {
        action = "send-to-workspace";
        arg = 6;
      };

      Super-8 = {
        action = "focus-workspace";
        arg = 7;
      };

      Super-Shift-8 = {
        action = "send-to-workspace";
        arg = 7;
      };

      Super-9 = {
        action = "focus-workspace";
        arg = 8;
      };

      Super-Shift-9 = {
        action = "send-to-workspace";
        arg = 8;
      };

      Super-0 = {
        action = "focus-workspace";
        arg = 9;
      };

      Super-Shift-0 = {
        action = "send-to-workspace";
        arg = 9;
      };
    };

    mousebinds = {
      Super-Left = "swap-tile";
      Super-Right = "resize-tile";
    };
  }
```

</details>

<details>
  <summary>View Full Config (TOML)</summary>

```toml
autostart = ["/nix/store/zihgs23bv7ixdkcsq0vxyzrbq80rr6zv-dex-0.10.1/bin/dex -a", "/nix/store/kblmy89fnirdndyz5aizf9ni9x4z6kmq-foot-1.21.0/bin/foot"]
imports = ["~/.config/fht/adhoc.toml"]

[env]
DISPLAY = ":0"
MOZ_ENABLE_WAYLAND = "1"
QT_QPA_PLATFORM = "wayland"
QT_QPA_PLATFORMTHEME = "gtk3"
QT_STYLE_OVERRIDE = "adwaita"
SDL_BACKEND = "wayland"
SDL_VIDEODRIVER = "wayland"
_JAVA_AWT_WM_NONREPARENTING = "1"

[general]
layouts = ["tile"]

[input]

[keybinds.Super-0]
action = "focus-workspace"
arg = 9

[keybinds.Super-1]
action = "focus-workspace"
arg = 0

[keybinds.Super-2]
action = "focus-workspace"
arg = 1

[keybinds.Super-3]
action = "focus-workspace"
arg = 2

[keybinds.Super-4]
action = "focus-workspace"
arg = 3

[keybinds.Super-5]
action = "focus-workspace"
arg = 4

[keybinds.Super-6]
action = "focus-workspace"
arg = 5

[keybinds.Super-7]
action = "focus-workspace"
arg = 6

[keybinds.Super-8]
action = "focus-workspace"
arg = 7

[keybinds.Super-9]
action = "focus-workspace"
arg = 8

[keybinds.Super-Control-Shift-q]
action = "quit"

[keybinds.Super-Control-Shift-r]
action = "reload-config"

[keybinds.Super-Return]
action = "run-command"
arg = "/nix/store/kblmy89fnirdndyz5aizf9ni9x4z6kmq-foot-1.21.0/bin/foot"

[keybinds.Super-Shift-0]
action = "send-to-workspace"
arg = 9

[keybinds.Super-Shift-1]
action = "send-to-workspace"
arg = 0

[keybinds.Super-Shift-2]
action = "send-to-workspace"
arg = 1

[keybinds.Super-Shift-3]
action = "send-to-workspace"
arg = 2

[keybinds.Super-Shift-4]
action = "send-to-workspace"
arg = 3

[keybinds.Super-Shift-5]
action = "send-to-workspace"
arg = 4

[keybinds.Super-Shift-6]
action = "send-to-workspace"
arg = 5

[keybinds.Super-Shift-7]
action = "send-to-workspace"
arg = 6

[keybinds.Super-Shift-8]
action = "send-to-workspace"
arg = 7

[keybinds.Super-Shift-9]
action = "send-to-workspace"
arg = 8

[keybinds.Super-Space]
action = "float-focused-window"

[keybinds.Super-c]
action = "center-floating-window"

[keybinds.Super-f]
action = "fullscreen-focused-window"

[keybinds.Super-m]
action = "maximize-focused-window"

[keybinds.Super-q]
action = "close-focused-window"

[mousebinds]
Super-Left = "swap-tile"
Super-Right = "resize-tile"
```

</details>
